id = "terragrunt-ls"
name = "terragrunt-ls"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "Terragrunt Language Server"
repository = "https://github.com/your-name/my-zed-extension"

[language_servers.terragrunt]
name = "Terragrunt LSP"
languages = ["Terragrunt"]
language_ids = {Terragrunt = "terragrunt"}
